language: go

go:
  - "1.13"

branches:
  only:
    - master
    - develop
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
  - redis-server

install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

before_script:
  - cp config/config_with_redis.json config/config.json

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)