version: "2"

services:
  go_mal_api:
    container_name: go-malscraper-container
    image: go-malscraper-image
    build:
      context: .
      dockerfile: ./build/package/Dockerfile
    ports:
      - 8005:8005
    tty: true