version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/redis

    branches:
      only:
        - master
        - develop
      ignore:
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

    working_directory: /go/src/github.com/rl404/go-malscraper

    steps:
      - checkout
      - run: cp config/config_with_redis.json config/config.json
      - run: go get -v -t -d ./...
      - run: go test -v ./...