version: "2"

services:
  malscraper-api:
    container_name: malscraper_container
    image: malscraper-image
    build:
      context: ./..
      dockerfile: ./build/package/Dockerfile
    ports:
      - 8005:8005
    tty: true
    links:
      - redis
  redis:
    image: redis